// This file was generated by silverstripe/tx-translator from client/lang/src/da_DK.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('da_DK', {
    "GRIDFIELD.ERRORINTRANSACTION": "Der opstod en fejl under hentning af data fra serveren\nPrøv igen senere.",
    "UserForms.ADDED_FIELD": "Tilføjede nyt felt",
    "UserForms.ADDED_OPTION": "Tilføjede option",
    "UserForms.ADDING_FIELD": "Tilføjer nyt felt",
    "UserForms.ADDING_OPTION": "Tilføjer option",
    "UserForms.ADDING_RULE": "Tilføjer regel",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle indsendelser vil blive permanent slettet. Vil du fortsætte?",
    "UserForms.ERROR_CONTAINER_HEADER": "Ret venligst følgende fejl, og prøv igen:",
    "UserForms.ERROR_CREATING_FIELD": "Fejl ved oprettelse af felt",
    "UserForms.ERROR_CREATING_OPTION": "Fejl ved oprettelse af option",
    "UserForms.HIDE_OPTIONS": "Skjul optioner",
    "UserForms.LEAVE_CONFIRMATION": "Du har ikke gemte ændringer!",
    "UserForms.REMOVED_OPTION": "Fjernede option",
    "UserForms.SHOW_OPTIONS": "Vis optioner"
});
}