// This file was generated by silverstripe/tx-translator from client/lang/src/de_DE.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('de_DE', {
    "GRIDFIELD.ERRORINTRANSACTION": "Ein Fehler ist beim Laden der Daten aufgetreten.\nBitte versuchen Sie es später nochmal.",
    "UserForms.ADDED_FIELD": "Neues Feld hinzugefügt",
    "UserForms.ADDED_OPTION": "Option hinzugefügt",
    "UserForms.ADDING_FIELD": "Neues Feld hinzugefügt",
    "UserForms.ADDING_OPTION": "Füge Option hinzu",
    "UserForms.ADDING_RULE": "Füge Regel hinzu",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle Einsendungen werden dauerhaft gelöscht. Wirklich fortfahren?",
    "UserForms.ERROR_CONTAINER_HEADER": "Please correct the following errors and try again:",
    "UserForms.ERROR_CREATING_FIELD": "Fehler beim erstellen des Feldes",
    "UserForms.ERROR_CREATING_OPTION": "Fehler beim erstellen der Option",
    "UserForms.HIDE_OPTIONS": "Optionen verbergen",
    "UserForms.LEAVE_CONFIRMATION": "You have unsaved changes!",
    "UserForms.REMOVED_OPTION": "Option entfernt",
    "UserForms.SHOW_OPTIONS": "Optionen anzeigen"
});
}