// This file was generated by silverstripe/cow from client/lang/src/fi_FI.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi_FI', {
    "GRIDFIELD.ERRORINTRANSACTION": "Tapahtui virhe noudettaessa tietoja palvelimelta\nOle hyvä ja yritä myöhemmin uudelleen.",
    "UserForms.ADDED_FIELD": "Lisätty uusi kenttä",
    "UserForms.ADDED_OPTION": "Valinta lisätty",
    "UserForms.ADDING_FIELD": "Lisätään uusi kenttä",
    "UserForms.ADDING_OPTION": "Lisätään valinta",
    "UserForms.ADDING_RULE": "Lisätään sääntö",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Kaikki lähetetyt viestit poistetaan pysyvästi. Jatketaanko?",
    "UserForms.ERROR_CREATING_FIELD": "Virhe luotaessa kenttää",
    "UserForms.ERROR_CREATING_OPTION": "Virhe luotaessa valintaa",
    "UserForms.HIDE_OPTIONS": "Piilota valinnat",
    "UserForms.LEAVE_CONFIRMATION": "Sinulla on tallentamattomia muutoksia!",
    "UserForms.REMOVED_OPTION": "Poistettiin valinta",
    "UserForms.SHOW_OPTIONS": "Näytä valinnat"
});
}