// This file was generated by silverstripe/tx-translator from client/lang/src/fr.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "GRIDFIELD.ERRORINTRANSACTION": "Une erreur est survenue durant la transaction avec le serveur\nMerci de réessayer plus tard.",
    "UserForms.ADDED_FIELD": "Nouveau champ ajouté",
    "UserForms.ADDED_OPTION": "Option ajoutée",
    "UserForms.ADDING_FIELD": "Ajout d'un nouveau champ",
    "UserForms.ADDING_OPTION": "Ajout d'une option",
    "UserForms.ADDING_RULE": "Ajout d'une règle",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Toutes les soumissions seront définitivement supprimées. Continuer ?",
    "UserForms.ERROR_CONTAINER_HEADER": "Veuillez corriger les erreurs suivantes et réessayer :",
    "UserForms.ERROR_CREATING_FIELD": "Erreur lors de la création du champ",
    "UserForms.ERROR_CREATING_OPTION": "Erreur lors de la création de l'option",
    "UserForms.HIDE_OPTIONS": "Masquer les options",
    "UserForms.LEAVE_CONFIRMATION": "Vous avez des changements non enregistrés !",
    "UserForms.REMOVED_OPTION": "Option supprimée",
    "UserForms.SHOW_OPTIONS": "Afficher les options"
});
}