// This file was generated by silverstripe/tx-translator from client/lang/src/id.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('id', {
    "UserForms.ADDED_OPTION": "Menambahkan Pilihan",
    "UserForms.ADDING_OPTION": "Menambahkan Pilihan",
    "UserForms.ADDING_RULE": "Menambahkan Aturan",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Semua pengiriman akan dihapus secara permanen. Lanjutkan?",
    "UserForms.HIDE_OPTIONS": "Sembunyikan Pilihan",
    "UserForms.SHOW_OPTIONS": "Menampilkan pilihan"
});
}