// This file was generated by silverstripe/tx-translator from client/lang/src/nb.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nb', {
    "GRIDFIELD.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "UserForms.ADDED_FIELD": "Added new field",
    "UserForms.ADDED_OPTION": "Added option",
    "UserForms.ADDING_FIELD": "Adding new field",
    "UserForms.ADDING_OPTION": "Adding option",
    "UserForms.ADDING_RULE": "Adding rule",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "All submissions will be permanently removed. Continue?",
    "UserForms.ERROR_CONTAINER_HEADER": "Please correct the following errors and try again:",
    "UserForms.ERROR_CREATING_FIELD": "Error creating field",
    "UserForms.ERROR_CREATING_OPTION": "Error creating option",
    "UserForms.HIDE_OPTIONS": "Hide options",
    "UserForms.LEAVE_CONFIRMATION": "You have unsaved changes!",
    "UserForms.REMOVED_OPTION": "Removed option",
    "UserForms.SHOW_OPTIONS": "Show options"
});
}