// This file was generated by silverstripe/tx-translator from client/lang/src/nb_NO.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nb_NO', {
    "GRIDFIELD.ERRORINTRANSACTION": "En feil har skjedd ved hent av data fra server.\nVennligst prøv igjen senere.",
    "UserForms.ADDED_FIELD": "Et nytt felt er lagt til",
    "UserForms.ADDED_OPTION": "Alternativ er lagt til",
    "UserForms.ADDING_FIELD": "Legg til nytt felt",
    "UserForms.ADDING_OPTION": "Legger til alternativ",
    "UserForms.ADDING_RULE": "Legger til regel",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle innsendinger vil bli permanent fjernet. Vil du forsette?",
    "UserForms.ERROR_CONTAINER_HEADER": "Please correct the following errors and try again:",
    "UserForms.ERROR_CREATING_FIELD": "En feil skjedde ved opprettelse felt",
    "UserForms.ERROR_CREATING_OPTION": "En feil skjedde ved opprettelse av alternativ",
    "UserForms.HIDE_OPTIONS": "Skjul alternativer",
    "UserForms.LEAVE_CONFIRMATION": "You have unsaved changes!",
    "UserForms.REMOVED_OPTION": "Alternativ er fjernet",
    "UserForms.SHOW_OPTIONS": "Vis alternativer"
});
}