// This file was generated by silverstripe/tx-translator from client/lang/src/nl.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "GRIDFIELD.ERRORINTRANSACTION": "Er is een fout opgetreden bij het ophalen van gegevens van de server\nProbeer later opnieuw.",
    "UserForms.ADDED_FIELD": "Nieuw veld toegevoegd",
    "UserForms.ADDED_OPTION": "Toegevoegde optie",
    "UserForms.ADDING_FIELD": "Nieuw veld toevoegen",
    "UserForms.ADDING_OPTION": "Optie toevoegen",
    "UserForms.ADDING_RULE": "Regel toevoegen",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle inzendingen zullen permanent worden verwijderd. Doorgaan?",
    "UserForms.ERROR_CONTAINER_HEADER": "Herstel de fouten en probeer het opnieuw:",
    "UserForms.ERROR_CREATING_FIELD": "Fout bij het maken veld",
    "UserForms.ERROR_CREATING_OPTION": "Fout bij het maken optie",
    "UserForms.HIDE_OPTIONS": "Verberg opties",
    "UserForms.LEAVE_CONFIRMATION": "Er zijn niet-opgeslagen wijzigingen!",
    "UserForms.REMOVED_OPTION": "Verwijderde optie",
    "UserForms.SHOW_OPTIONS": "Toon opties"
});
}