// This file was generated by silverstripe/tx-translator from client/lang/src/nl_NL.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl_NL', {
    "GRIDFIELD.ERRORINTRANSACTION": "Er is een fout opgetreden tijdens het ophalen van gegevens van de server.\nProbeer het later opnieuw.",
    "UserForms.ADDED_FIELD": "Nieuw veld toegevoegd",
    "UserForms.ADDED_OPTION": "Toegevoegde optie",
    "UserForms.ADDING_FIELD": "Nieuw veld toe te voegen",
    "UserForms.ADDING_OPTION": "Nieuwe optie toevoegen",
    "UserForms.ADDING_RULE": "Regel toevoegen",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle inzendingen zullen permanent worden verwijderd. Doorgaan?",
    "UserForms.ERROR_CONTAINER_HEADER": "Please correct the following errors and try again:",
    "UserForms.ERROR_CREATING_FIELD": "Fout bij het maken optie",
    "UserForms.ERROR_CREATING_OPTION": "Fout bij het maken optie",
    "UserForms.HIDE_OPTIONS": "Verberg opties",
    "UserForms.LEAVE_CONFIRMATION": "You have unsaved changes!",
    "UserForms.REMOVED_OPTION": "Verwijder optie",
    "UserForms.SHOW_OPTIONS": "Toon opties"
});
}