// This file was generated by silverstripe/tx-translator from client/lang/src/sk.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "GRIDFIELD.ERRORINTRANSACTION": "Nastala chyba pri získavaní dát zo servera.\nProsím, skúste to neskôr.",
    "UserForms.ADDED_FIELD": "Nové políčko pridané",
    "UserForms.ADDED_OPTION": "Voľba/možnosť pridaná",
    "UserForms.ADDING_FIELD": "Pridávanie nového políčka",
    "UserForms.ADDING_OPTION": "Pridávanie voľby/možnosti",
    "UserForms.ADDING_RULE": "Pravidlo priadné",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Všetky podané formuláre budú permanentne odstránené. Pokračovať?",
    "UserForms.ERROR_CONTAINER_HEADER": "Please correct the following errors and try again:",
    "UserForms.ERROR_CREATING_FIELD": "Nastala chyba pri vytváraní poľa",
    "UserForms.ERROR_CREATING_OPTION": "Nastala chyba pri vytváraní voľby/možnosti",
    "UserForms.HIDE_OPTIONS": "Skryť možnosti",
    "UserForms.LEAVE_CONFIRMATION": "Máte neuložené zmeny!",
    "UserForms.REMOVED_OPTION": "Voľba/možnosť odstránená",
    "UserForms.SHOW_OPTIONS": "Zobraziť možnosti"
});
}