// This file was generated by silverstripe/tx-translator from client/lang/src/sl.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "GRIDFIELD.ERRORINTRANSACTION": "Napaka pri pridobivanju podatkov s strežnika. Poskusite ponovno.",
    "UserForms.ADDED_FIELD": "Dodano novo polje",
    "UserForms.ADDED_OPTION": "Dodana možnost",
    "UserForms.ADDING_FIELD": "Dodajam novo polje",
    "UserForms.ADDING_OPTION": "Možnost dodajanja",
    "UserForms.ADDING_RULE": "Pravilo dodajanja",
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Vsi oddani obrazci bodo dokončno odstranjeni. Nadaljuj?",
    "UserForms.ERROR_CONTAINER_HEADER": "Prosimo, popravite naslednje napake in nato poskusite znova:",
    "UserForms.ERROR_CREATING_FIELD": "Napaka pri ustvarjanju polja",
    "UserForms.ERROR_CREATING_OPTION": "Napaka pri ustvarjanju možnosti",
    "UserForms.HIDE_OPTIONS": "Skrij možnosti",
    "UserForms.LEAVE_CONFIRMATION": "Spremembe niso bile shranjene!",
    "UserForms.REMOVED_OPTION": "Odstranjena možnost",
    "UserForms.SHOW_OPTIONS": "Prikaži možnosti"
});
}