// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ar.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ar', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "ستتم إزالة جميع الطلبات المقدمة بشكل دائم. المتابعة؟",
    "UserForms.ERROR_CREATING_FIELD": "خطأ في إنشاء الحقل",
    "UserForms.ADDING_FIELD": "إضافة حقل جديد",
    "UserForms.ADDED_FIELD": "أضيف حقل جديد",
    "UserForms.HIDE_OPTIONS": "إخفاء الخيارات",
    "UserForms.SHOW_OPTIONS": "إظهار الخيارات",
    "UserForms.ADDING_OPTION": "إضافة خيار",
    "UserForms.ADDED_OPTION": "الخيار المضاف",
    "UserForms.ERROR_CREATING_OPTION": "خطأ في إنشاء الخيار",
    "UserForms.REMOVED_OPTION": "تمت إزالة الخيار",
    "UserForms.ADDING_RULE": "إضافة قاعدة",
    "GRIDFIELD.ERRORINTRANSACTION": "حدث خطأ أثناء جلب البيانات من الملقم\nيرجى المحاولة مرة أخرى في وقت لاحق."
});
}