// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/de_DE.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('de_DE', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle Einsendungen werden dauerhaft gelöscht. Wirklich fortfahren?",
    "UserForms.ERROR_CREATING_FIELD": "Fehler beim erstellen des Feldes",
    "UserForms.ADDING_FIELD": "Neues Feld hinzugefügt",
    "UserForms.ADDED_FIELD": "Neues Feld hinzugefügt",
    "UserForms.HIDE_OPTIONS": "Optionen verbergen",
    "UserForms.SHOW_OPTIONS": "Optionen anzeigen",
    "UserForms.ADDING_OPTION": "Füge Option hinzu",
    "UserForms.ADDED_OPTION": "Option hinzugefügt",
    "UserForms.ERROR_CREATING_OPTION": "Fehler beim erstellen der Option",
    "UserForms.REMOVED_OPTION": "Option entfernt",
    "UserForms.ADDING_RULE": "Füge Regel hinzu",
    "GRIDFIELD.ERRORINTRANSACTION": "Ein Fehler ist beim Laden der Daten aufgetreten.\nBitte versuchen Sie es später nochmal."
});
}