// This file was generated by silverstripe/cow from javascript/lang/src/en.js.
// See https://github.com/tractorcow/cow for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('en', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "All submissions will be permanently removed. Continue?",
    "UserForms.ERROR_CREATING_FIELD": "Error creating field",
    "UserForms.ADDING_FIELD": "Adding new field",
    "UserForms.ADDED_FIELD": "Added new field",
    "UserForms.HIDE_OPTIONS": "Hide options",
    "UserForms.SHOW_OPTIONS": "Show options",
    "UserForms.ADDING_OPTION": "Adding option",
    "UserForms.ADDED_OPTION": "Added option",
    "UserForms.ERROR_CREATING_OPTION": "Error creating option",
    "UserForms.REMOVED_OPTION": "Removed option",
    "UserForms.ADDING_RULE": "Adding rule",
    "UserForms.LEAVE_CONFIRMATION": "You have unsaved changes!",
    "GRIDFIELD.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later."
});
}
