// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/eo.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('eo', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Ĉiuj sendaĵoj malaperos porĉiame. Ĉu daŭrigu?",
    "UserForms.ERROR_CREATING_FIELD": "Eraris kreante kampon",
    "UserForms.ADDING_FIELD": "Aldonas novan kampon",
    "UserForms.ADDED_FIELD": "Aldonis novan kampon",
    "UserForms.HIDE_OPTIONS": "Kaŝi agordojn",
    "UserForms.SHOW_OPTIONS": "Vidigi agordojn",
    "UserForms.ADDING_OPTION": "Aldonas agordon",
    "UserForms.ADDED_OPTION": "Aldonis agordon",
    "UserForms.ERROR_CREATING_OPTION": "Eraris kreante agordon",
    "UserForms.REMOVED_OPTION": "Forigis agordon",
    "UserForms.ADDING_RULE": "Aldonas regulon",
    "GRIDFIELD.ERRORINTRANSACTION": "Eraris venigante datumojn el la servilo.\nBonvolu reprovi poste."
});
}