// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/fi_FI.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('fi_FI', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Kaikki lähetetyt viestit poistetaan pysyvästi. Jatketaanko?",
    "UserForms.ERROR_CREATING_FIELD": "Virhe luotaessa kenttää",
    "UserForms.ADDING_FIELD": "Lisätään uusi kenttä",
    "UserForms.ADDED_FIELD": "Lisätty uusi kenttä",
    "UserForms.HIDE_OPTIONS": "Piilota valinnat",
    "UserForms.SHOW_OPTIONS": "Näytä valinnat",
    "UserForms.ADDING_OPTION": "Lisätään valinta",
    "UserForms.ADDED_OPTION": "Valinta lisätty",
    "UserForms.ERROR_CREATING_OPTION": "Virhe luotaessa valintaa",
    "UserForms.REMOVED_OPTION": "Poistettiin valinta",
    "UserForms.ADDING_RULE": "Lisätään sääntö",
    "GRIDFIELD.ERRORINTRANSACTION": "Tapahtui virhe noudettaessa tietoja palvelimelta\nOle hyvä ja yritä myöhemmin uudelleen."
});
}