// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/id.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('id', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Semua pengiriman akan dihapus secara permanen. Lanjutkan?",
    "UserForms.ERROR_CREATING_FIELD": "Error creating field",
    "UserForms.ADDING_FIELD": "Adding new field",
    "UserForms.ADDED_FIELD": "Added new field",
    "UserForms.HIDE_OPTIONS": "Sembunyikan Pilihan",
    "UserForms.SHOW_OPTIONS": "Menampilkan pilihan",
    "UserForms.ADDING_OPTION": "Menambahkan Pilihan",
    "UserForms.ADDED_OPTION": "Menambahkan Pilihan",
    "UserForms.ERROR_CREATING_OPTION": "Error creating option",
    "UserForms.REMOVED_OPTION": "Removed option",
    "UserForms.ADDING_RULE": "Menambahkan Aturan",
    "GRIDFIELD.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later."
});
}