// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/mi.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('mi', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Ka muku pūmautia ngā tukunga katoa. Me haere tonu?",
    "UserForms.ERROR_CREATING_FIELD": "Hapa hanga āpure",
    "UserForms.ADDING_FIELD": "Tāpiri āpure hou ana",
    "UserForms.ADDED_FIELD": "Kua tāpiritia he āpure hou",
    "UserForms.HIDE_OPTIONS": "Hunaia ngā kōwhiringa",
    "UserForms.SHOW_OPTIONS": "Whakaatu Kōwhiringa",
    "UserForms.ADDING_OPTION": "Tāpiri kōwhiringa ana",
    "UserForms.ADDED_OPTION": "Kua tāpiri kōwhiringa",
    "UserForms.ERROR_CREATING_OPTION": "Hapa hanga kōwhiringa",
    "UserForms.REMOVED_OPTION": "Kua tango kōwhiringa",
    "UserForms.ADDING_RULE": "Tāpiri ture ana",
    "GRIDFIELD.ERRORINTRANSACTION": "Kua puta mai he hapa i te tiki raraunga mai i te tūmau\n Ngāna anō ā muri atu."
});
}