// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/nb_NO.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('nb_NO', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alle innsendinger vil bli permanent fjernet. Vil du forsette?",
    "UserForms.ERROR_CREATING_FIELD": "En feil skjedde ved opprettelse felt",
    "UserForms.ADDING_FIELD": "Legg til nytt felt",
    "UserForms.ADDED_FIELD": "Et nytt felt er lagt til",
    "UserForms.HIDE_OPTIONS": "Skjul alternativer",
    "UserForms.SHOW_OPTIONS": "Vis alternativer",
    "UserForms.ADDING_OPTION": "Legger til alternativ",
    "UserForms.ADDED_OPTION": "Alternativ er lagt til",
    "UserForms.ERROR_CREATING_OPTION": "En feil skjedde ved opprettelse av alternativ",
    "UserForms.REMOVED_OPTION": "Alternativ er fjernet",
    "UserForms.ADDING_RULE": "Legger til regel",
    "GRIDFIELD.ERRORINTRANSACTION": "En feil har skjedd ved hent av data fra server.\nVennligst prøv igjen senere."
});
}