// This file was generated by silverstripe/cow from javascript/lang/src/sk.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Všetky podané formuláre budú permanentne odstránené. Pokračovať?",
    "UserForms.ERROR_CREATING_FIELD": "Nastala chyba pri vytváraní poľa",
    "UserForms.ADDING_FIELD": "Pridávanie nového políčka",
    "UserForms.ADDED_FIELD": "Nové políčko pridané",
    "UserForms.HIDE_OPTIONS": "Skryť možnosti",
    "UserForms.SHOW_OPTIONS": "Zobraziť možnosti",
    "UserForms.ADDING_OPTION": "Pridávanie voľby/možnosti",
    "UserForms.ADDED_OPTION": "Voľba/možnosť pridaná",
    "UserForms.ERROR_CREATING_OPTION": "Nastala chyba pri vytváraní voľby/možnosti",
    "UserForms.REMOVED_OPTION": "Voľba/možnosť odstránená",
    "UserForms.ADDING_RULE": "Pravidlo priadné",
    "GRIDFIELD.ERRORINTRANSACTION": "Nastala chyba pri získavaní dát zo servera.\nProsím, skúste to neskôr."
});
}