// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/sv.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('sv', {
    "UserForms.CONFIRM_DELETE_ALL_SUBMISSIONS": "Alla inskickade svar kommer att tas bort permanent. Vill du fortsätta?",
    "UserForms.ERROR_CREATING_FIELD": "Fel när fält skapades",
    "UserForms.ADDING_FIELD": "Lägger till nytt fält",
    "UserForms.ADDED_FIELD": "La till nytt fält",
    "UserForms.HIDE_OPTIONS": "Göm alternativ",
    "UserForms.SHOW_OPTIONS": "Visa alternativ",
    "UserForms.ADDING_OPTION": "Lägger till alternativ",
    "UserForms.ADDED_OPTION": "La till alternativ",
    "UserForms.ERROR_CREATING_OPTION": "Fel när alternativ skapades",
    "UserForms.REMOVED_OPTION": "Raderade alternativ",
    "UserForms.ADDING_RULE": "Lägger till regel",
    "GRIDFIELD.ERRORINTRANSACTION": "Ett fel uppstod när data hämtades från servern.\nVar god försök igen senare."
});
}