name: Update JS

on:
  workflow_dispatch:
  # At 12:00 PM UTC, on day 1 of the month, only in March and September
  schedule:
    - cron: '0 12 1 3,9 *'

permissions: {}

jobs:
  update-js:
    name: Update JS
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Update JS
        uses: silverstripe/gha-update-js@v1
